### ISSUE TITLE
F-10-OUTFIT-UI

### ISSUE THREAD

**Issue by TheMisterPin** [TheMisterPin/wardrobe-manager#17]
# Front End Task 10 Oufit UI 

## Desired Outcome 
To enhance the outfit ui with new features 

## Tasks 
- [ ] user can add a picture while wearing the outfit 
- [ ] can rename the outfit
- [ ] can add occasion to the outfit 
- [ ] can download picture of the outfit
