### ISSUE TITLE
B-04-OCCASION

### ISSUE THREAD

**Issue by TheMisterPin** [TheMisterPin/wardrobe-manager#21]
# Backend Task Occasion 
### Branch 
 ```bash 
git fetch origin
git checkout 21-b-04-occasion

```

## Desired Outcome 
To Implement the backend logic for objects to be sorted and returned based on occasion 

## Roadmap 
Building a solid base for future implementeation and sorting. 

## Tasks 
- [ ] Added the enum Occasion to the schema 
```typescript 
enum Occasion {
  WORK
CASUAL 
FORMAL 
SPORT 
}
```
- [ ] Can change Occasion 
- [ ] FIltered Objects in Response 
- [ ] Filtered Outfits in Response
