### ISSUE TITLE
F-12-BLOBS

### ISSUE THREAD

**Issue by TheMisterPin** [TheMisterPin/wardrobe-manager#27]
# Frontend Task #12 : Outfit Blobs 

### Branch 

```
git fetch origin
git checkout 27-f-12-blobs
```

## Desired outcome 
To create a more visually attractive blob for the outfits, ideally with a series of utility functions. 
The end result should be to have different types of outfit dislayed in a striking way. 
Might have to change the shape of objects in the database in the future, for now lets just standarize the view by having the items stacked on the preview 

## Tasks 

- [ ]  Write utility funcion called when creating outfit 
- [ ]  Write utlitiy function to create different blob at runtime with different disposition 
- [ ]  Implement utility functions in form and cards
